### PR TITLE
Fix downloading of versions with prefix

### PR DESCRIPTION
**Pull request by bforchhammer**

### CODE REVIEW

**Comment by bforchhammer** [comment]
I think travis is failing because of the github rate limiting...

**Comment by thuandt** [comment]
LGTM :+1:

**Review by stefansedich — APPROVED** [review]

**Comment by stefansedich** [comment]
Sorry all for some reason these slipped by me :cry: never saw any notifications, I think the build is failing cause of token will fix that up.

**Comment by bforchhammer** [comment]
Thanks for merging :heart:

**Pull request merged**
